version: '3.8'
services:
    rasa:
      image: rasa/rasa:2.8.2
      volumes:
        - ./:/app/
      ports:
        - 5005:5005
      command: 
        - run
        - --cors
        - "*"
        - --enable-api

    action_server:
      image: rasa/rasa-sdk:2.8.2
      volumes:
        - ./actions:/app/actions
      ports: 
        - "5055:5055"